# Generated by Django 4.2.5 on 2023-09-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advert', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvert',
            name='tag',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
