# Generated by Django 4.2.5 on 2023-09-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advert', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caradvert',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='caradvert',
            name='id',
            field=models.CharField(default='673c2b17-e804-415a-9d1a-fa622904e733', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
