# Generated by Django 4.2.5 on 2023-09-17 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advert', '0003_caradvert_is_active_alter_caradvert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvert',
            name='id',
            field=models.CharField(default='ddbbde67-a761-4d76-8c9c-b942055fc9dd', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
