# Generated by Django 4.2.5 on 2023-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_advert', '0004_alter_caradvert_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caradvert',
            name='id',
            field=models.CharField(default='1bf15821-c5c2-404d-be0b-bcef69b1756b', editable=False, max_length=36, primary_key=True, serialize=False, unique=True),
        ),
    ]
