# Generated by Django 4.2.5 on 2023-09-18 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='', max_length=11, validators=[django.core.validators.MinLengthValidator(limit_value=11)]),
        ),
    ]
