# Generated by Django 4.2.5 on 2023-09-17 17:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
