# Generated by Django 4.2.5 on 2023-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_brand', '0002_carbrand_created_at_carbrand_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbrand',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
