# Generated by Django 4.2.5 on 2023-09-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_model', '0002_carmodel_created_at_carmodel_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
